/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by genmsg_cpp from file /home/luc/ros_workspace/alg_robo_p2/catkin/src/algp2_msgs/msg/Map2D.msg
 *
 */


#ifndef ALGP2_MSGS_MESSAGE_MAP2D_H
#define ALGP2_MSGS_MESSAGE_MAP2D_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Int8MultiArray.h>

namespace algp2_msgs
{
template <class ContainerAllocator>
struct Map2D_
{
  typedef Map2D_<ContainerAllocator> Type;

  Map2D_()
    : columns()  {
    }
  Map2D_(const ContainerAllocator& _alloc)
    : columns(_alloc)  {
    }



   typedef std::vector< ::std_msgs::Int8MultiArray_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::std_msgs::Int8MultiArray_<ContainerAllocator> >::other >  _columns_type;
  _columns_type columns;




  typedef boost::shared_ptr< ::algp2_msgs::Map2D_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::algp2_msgs::Map2D_<ContainerAllocator> const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;

}; // struct Map2D_

typedef ::algp2_msgs::Map2D_<std::allocator<void> > Map2D;

typedef boost::shared_ptr< ::algp2_msgs::Map2D > Map2DPtr;
typedef boost::shared_ptr< ::algp2_msgs::Map2D const> Map2DConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::algp2_msgs::Map2D_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::algp2_msgs::Map2D_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace algp2_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'nav_msgs': ['/opt/ros/hydro/share/nav_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/hydro/share/geometry_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/hydro/share/actionlib_msgs/cmake/../msg'], 'algp2_msgs': ['/home/luc/ros_workspace/alg_robo_p2/catkin/src/algp2_msgs/msg'], 'std_msgs': ['/opt/ros/hydro/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::algp2_msgs::Map2D_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::algp2_msgs::Map2D_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::algp2_msgs::Map2D_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::algp2_msgs::Map2D_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::algp2_msgs::Map2D_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::algp2_msgs::Map2D_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::algp2_msgs::Map2D_<ContainerAllocator> >
{
  static const char* value()
  {
    return "db42e0320f0430c95b1e0ec660057b45";
  }

  static const char* value(const ::algp2_msgs::Map2D_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xdb42e0320f0430c9ULL;
  static const uint64_t static_value2 = 0x5b1e0ec660057b45ULL;
};

template<class ContainerAllocator>
struct DataType< ::algp2_msgs::Map2D_<ContainerAllocator> >
{
  static const char* value()
  {
    return "algp2_msgs/Map2D";
  }

  static const char* value(const ::algp2_msgs::Map2D_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::algp2_msgs::Map2D_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Message to create a vector of vectors to store map data to be sent to the global planner.\n\
\n\
std_msgs/Int8MultiArray[] columns\n\
================================================================================\n\
MSG: std_msgs/Int8MultiArray\n\
# Please look at the MultiArrayLayout message definition for\n\
# documentation on all multiarrays.\n\
\n\
MultiArrayLayout  layout        # specification of data layout\n\
int8[]            data          # array of data\n\
\n\
\n\
================================================================================\n\
MSG: std_msgs/MultiArrayLayout\n\
# The multiarray declares a generic multi-dimensional array of a\n\
# particular data type.  Dimensions are ordered from outer most\n\
# to inner most.\n\
\n\
MultiArrayDimension[] dim # Array of dimension properties\n\
uint32 data_offset        # padding bytes at front of data\n\
\n\
# Accessors should ALWAYS be written in terms of dimension stride\n\
# and specified outer-most dimension first.\n\
# \n\
# multiarray(i,j,k) = data[data_offset + dim_stride[1]*i + dim_stride[2]*j + k]\n\
#\n\
# A standard, 3-channel 640x480 image with interleaved color channels\n\
# would be specified as:\n\
#\n\
# dim[0].label  = \"height\"\n\
# dim[0].size   = 480\n\
# dim[0].stride = 3*640*480 = 921600  (note dim[0] stride is just size of image)\n\
# dim[1].label  = \"width\"\n\
# dim[1].size   = 640\n\
# dim[1].stride = 3*640 = 1920\n\
# dim[2].label  = \"channel\"\n\
# dim[2].size   = 3\n\
# dim[2].stride = 3\n\
#\n\
# multiarray(i,j,k) refers to the ith row, jth column, and kth channel.\n\
================================================================================\n\
MSG: std_msgs/MultiArrayDimension\n\
string label   # label of given dimension\n\
uint32 size    # size of given dimension (in type units)\n\
uint32 stride  # stride of given dimension\n\
";
  }

  static const char* value(const ::algp2_msgs::Map2D_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::algp2_msgs::Map2D_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.columns);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct Map2D_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::algp2_msgs::Map2D_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::algp2_msgs::Map2D_<ContainerAllocator>& v)
  {
    s << indent << "columns[]" << std::endl;
    for (size_t i = 0; i < v.columns.size(); ++i)
    {
      s << indent << "  columns[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::std_msgs::Int8MultiArray_<ContainerAllocator> >::stream(s, indent + "    ", v.columns[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // ALGP2_MSGS_MESSAGE_MAP2D_H
